    let v=[    
        {field:"0",contentType:"n",maxLen:4,lenType:"FIXED",description:"MTI",action:"System"},
        {field:"1",contentType:"b",maxLen:8,lenType:"FIXED",description:"Bitmap",action:"System"},
        {field:"2",contentType:"n",maxLen:19,lenType:"LLVAR",description:"Primary account number (PAN)",action:"System"},
        {field:"3",contentType:"n",maxLen:6,lenType:"FIXED",description:"Processing code",action:"System"},
        {field:"4",contentType:"n",maxLen:12,lenType:"FIXED",description:"Amount, transaction",action:"System"},
        {field:"5",contentType:"n",maxLen:12,lenType:"FIXED",description:"Amount, settlement",action:"System"},
        {field:"6",contentType:"n",maxLen:12,lenType:"FIXED",description:"Amount, cardholder billing",action:"System"},
        {field:"7",contentType:"n",maxLen:10,lenType:"FIXED",description:"Transmission date & time (MMDDhhmmss)",action:"System"},
        {field:"8",contentType:"n",maxLen:8,lenType:"FIXED",description:"Amount, cardholder billing fee",action:"System"},
        {field:"9",contentType:"n",maxLen:8,lenType:"FIXED",description:"Conversion rate, settlement",action:"System"},
        {field:"10",contentType:"n",maxLen:8,lenType:"FIXED",description:"Conversion rate, cardholder billing",action:"System"},
        {field:"11",contentType:"n",maxLen:6,lenType:"FIXED",description:"System trace audit number",action:"System"},
        {field:"12",contentType:"n",maxLen:12,lenType:"FIXED",description:"Time, local transaction (YYMMDDhhmmss)",action:"System"},
        {field:"13",contentType:"n",maxLen:4,lenType:"FIXED",description:"Date, local transaction (MMDD)",action:"System"},
        {field:"14",contentType:"n",maxLen:4,lenType:"FIXED",description:"Date, expiration",action:"System"},
        {field:"15",contentType:"n",maxLen:6,lenType:"FIXED",description:"Date, settlement",action:"System"},
        {field:"16",contentType:"n",maxLen:4,lenType:"FIXED",description:"Date, conversion",action:"System"},
        {field:"17",contentType:"n",maxLen:4,lenType:"FIXED",description:"Date, capture",action:"System"},
        {field:"18",contentType:"n",maxLen:4,lenType:"FIXED",description:"Merchant type",action:"System"},
        {field:"19",contentType:"n",maxLen:3,lenType:"FIXED",description:"Acquiring institution country code",action:"System"},
        {field:"20",contentType:"n",maxLen:3,lenType:"FIXED",description:"PAN extended, country code",action:"System"},
        {field:"21",contentType:"n",maxLen:3,lenType:"FIXED",description:"Forwarding institution. country code",action:"System"},
        {field:"22",contentType:"n",maxLen:3,lenType:"FIXED",description:"Point of service entry mode",action:"System"},
        {field:"23",contentType:"n",maxLen:3,lenType:"FIXED",description:"Application PAN sequence number",action:"System"},
        {field:"24",contentType:"n",maxLen:3,lenType:"FIXED",description:"Network International identifier (NII)",action:"System"},
        {field:"25",contentType:"n",maxLen:2,lenType:"FIXED",description:"Point of service condition code",action:"System"},
        {field:"26",contentType:"n",maxLen:2,lenType:"FIXED",description:"Point of service capture code",action:"System"},
        {field:"27",contentType:"n",maxLen:1,lenType:"FIXED",description:"Authorizing identification response length",action:"System"},
        {field:"28",contentType:"an",maxLen:9,lenType:"FIXED",description:"Amount, transaction fee",action:"System"},
        {field:"29",contentType:"an",maxLen:9,lenType:"FIXED",description:"Amount, settlement fee",action:"System"},
        {field:"30",contentType:"an",maxLen:9,lenType:"FIXED",description:"Amount, transaction processing fee",action:"System"},
        {field:"31",contentType:"an",maxLen:9,lenType:"FIXED",description:"Amount, settlement processing fee",action:"System"},
        {field:"32",contentType:"n",maxLen:11,lenType:"LLVAR",description:"Acquiring institution identification code",action:"System"},
        {field:"33",contentType:"n",maxLen:11,lenType:"LLVAR",description:"Forwarding institution identification code",action:"System"},
        {field:"34",contentType:"ns",maxLen:28,lenType:"LLVAR",description:"Primary account number, extended",action:"System"},
        {field:"35",contentType:"z",maxLen:37,lenType:"LLVAR",description:"Track 2 data",action:"System"},
        {field:"36",contentType:"n",maxLen:104,lenType:"LLLVAR",description:"Track 3 data",action:"System"},
        {field:"37",contentType:"an",maxLen:12,lenType:"FIXED",description:"Retrieval reference number",action:"System"},
        {field:"38",contentType:"an",maxLen:6,lenType:"FIXED",description:"Authorization identification response",action:"System"},
        {field:"39",contentType:"an",maxLen:3,lenType:"FIXED",description:"Response code",action:"System"},
        {field:"40",contentType:"an",maxLen:3,lenType:"FIXED",description:"Service restriction code",action:"System"},
        {field:"41",contentType:"ans",maxLen:8,lenType:"FIXED",description:"Terminal ID",action:"System"},
        {field:"42",contentType:"ans",maxLen:15,lenType:"FIXED",description:"Merchant number",action:"System"},
        {field:"43",contentType:"ans",maxLen:40,lenType:"FIXED",description:"Card acceptor name/location",action:"System"},
        {field:"44",contentType:"an",maxLen:25,lenType:"LLVAR",description:"Additional response data",action:"System"},
        {field:"45",contentType:"an",maxLen:76,lenType:"LLVAR",description:"Track 1 data",action:"System"},
        {field:"46",contentType:"an",maxLen:999,lenType:"LLLVAR",description:"Amount, fees",action:"System"},
        {field:"47",contentType:"an",maxLen:999,lenType:"LLLVAR",description:"Additional data",action:"System"},
        {field:"48",contentType:"an",maxLen:999,lenType:"LLLVAR",description:"Additional data - private",action:"System"},
        {field:"49",contentType:"an",maxLen:3,lenType:"FIXED",description:"Currency code, transaction",action:"System"},
        {field:"50",contentType:"an",maxLen:3,lenType:"FIXED",description:"Currency code, settlement",action:"System"},
        {field:"51",contentType:"an",maxLen:3,lenType:"FIXED",description:"Currency code, cardholder billing",action:"System"},
        {field:"52",contentType:"b",maxLen:16,lenType:"FIXED",description:"PIN data",action:"System"},
        {field:"53",contentType:"an",maxLen:99,lenType:"LLVAR",description:"Security related control information",action:"System"},
        {field:"54",contentType:"an",maxLen:120,lenType:"LLLVAR",description:"Additional amounts",action:"System"},
        {field:"55",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"ICC Sys Related Data",action:"System"},
        {field:"56",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved ISO",action:"System"},
        {field:"57",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved national",action:"System"},
        {field:"58",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved national",action:"System"},
        {field:"59",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved national",action:"System"},
        {field:"60",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved national",action:"System"},
        {field:"61",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved private",action:"System"},
        {field:"62",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved private",action:"System"},
        {field:"63",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved private",action:"System"},
        {field:"64",contentType:"b",maxLen:8,lenType:"FIXED",description:"Message authentication code (MAC)",action:"System"},
        {field:"65",contentType:"b",maxLen:1,lenType:"FIXED",description:"Bitmap, extended",action:"System"},
        {field:"66",contentType:"n",maxLen:1,lenType:"FIXED",description:"Settlement code",action:"System"},
        {field:"67",contentType:"n",maxLen:2,lenType:"FIXED",description:"Extended payment code",action:"System"},
        {field:"68",contentType:"n",maxLen:3,lenType:"FIXED",description:"Receiving institution country code",action:"System"},
        {field:"69",contentType:"n",maxLen:3,lenType:"FIXED",description:"Settlement institution country code",action:"System"},
        {field:"70",contentType:"n",maxLen:3,lenType:"FIXED",description:"Network management information code",action:"System"},
        {field:"71",contentType:"n",maxLen:4,lenType:"FIXED",description:"Message number",action:"System"},
        {field:"72",contentType:"n",maxLen:4,lenType:"FIXED",description:"Message number, last",action:"System"},
        {field:"73",contentType:"n",maxLen:6,lenType:"FIXED",description:"Date, action (YYMMDD)",action:"System"},
        {field:"74",contentType:"n",maxLen:10,lenType:"FIXED",description:"Credits, number",action:"System"},
        {field:"75",contentType:"n",maxLen:10,lenType:"FIXED",description:"Credits, reversal number",action:"System"},
        {field:"76",contentType:"n",maxLen:10,lenType:"FIXED",description:"Debits, number",action:"System"},
        {field:"77",contentType:"n",maxLen:10,lenType:"FIXED",description:"Debits, reversal number",action:"System"},
        {field:"78",contentType:"n",maxLen:10,lenType:"FIXED",description:"Transfer number",action:"System"},
        {field:"79",contentType:"n",maxLen:10,lenType:"FIXED",description:"Transfer, reversal number",action:"System"},
        {field:"80",contentType:"n",maxLen:10,lenType:"FIXED",description:"Inquiries number",action:"System"},
        {field:"81",contentType:"n",maxLen:10,lenType:"FIXED",description:"Authorizations, number",action:"System"},
        {field:"82",contentType:"n",maxLen:12,lenType:"FIXED",description:"Credits, processing fee amount",action:"System"},
        {field:"83",contentType:"n",maxLen:12,lenType:"FIXED",description:"Credits, transaction fee amount",action:"System"},
        {field:"84",contentType:"n",maxLen:12,lenType:"FIXED",description:"Debits, processing fee amount",action:"System"},
        {field:"85",contentType:"n",maxLen:12,lenType:"FIXED",description:"Debits, transaction fee amount",action:"System"},
        {field:"86",contentType:"n",maxLen:16,lenType:"FIXED",description:"Credits, amount",action:"System"},
        {field:"87",contentType:"n",maxLen:16,lenType:"FIXED",description:"Credits, reversal amount",action:"System"},
        {field:"88",contentType:"n",maxLen:16,lenType:"FIXED",description:"Debits, amount",action:"System"},
        {field:"89",contentType:"n",maxLen:16,lenType:"FIXED",description:"Debits, reversal amount",action:"System"},
        {field:"90",contentType:"n",maxLen:42,lenType:"FIXED",description:"Original data elements",action:"System"},
        {field:"91",contentType:"an",maxLen:1,lenType:"FIXED",description:"File update code",action:"System"},
        {field:"92",contentType:"an",maxLen:2,lenType:"FIXED",description:"File security code",action:"System"},
        {field:"93",contentType:"an",maxLen:5,lenType:"FIXED",description:"Response indicator",action:"System"},
        {field:"94",contentType:"an",maxLen:7,lenType:"FIXED",description:"Service indicator",action:"System"},
        {field:"95",contentType:"an",maxLen:42,lenType:"FIXED",description:"Replacement amounts",action:"System"},
        {field:"96",contentType:"b",maxLen:8,lenType:"FIXED",description:"Message security code",action:"System"},
        {field:"97",contentType:"an",maxLen:17,lenType:"FIXED",description:"Amount, net settlement",action:"System"},
        {field:"98",contentType:"ans",maxLen:25,lenType:"FIXED",description:"Payee",action:"System"},
        {field:"99",contentType:"n",maxLen:11,lenType:"LLVAR",description:"Settlement institution identification code",action:"System"},
        {field:"100",contentType:"n",maxLen:11,lenType:"LLVAR",description:"Receiving institution identification code",action:"System"},
        {field:"101",contentType:"ans",maxLen:17,lenType:"LLVAR",description:"File name",action:"System"},
        {field:"102",contentType:"ans",maxLen:28,lenType:"LLVAR",description:"Account identification 1",action:"System"},
        {field:"103",contentType:"ans",maxLen:28,lenType:"LLVAR",description:"Account identification 2",action:"System"},
        {field:"104",contentType:"ans",maxLen:100,lenType:"LLLVAR",description:"Transaction description",action:"System"},
        {field:"105",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"106",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"107",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"108",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"109",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"110",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"111",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for ISO use",action:"System"},
        {field:"112",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"113",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"114",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"115",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"116",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"117",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"118",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"119",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for national use",action:"System"},
        {field:"120",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"121",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"122",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"123",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"124",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"125",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"126",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"127",contentType:"ans",maxLen:999,lenType:"LLLVAR",description:"Reserved for private use",action:"System"},
        {field:"128",contentType:"b",maxLen:8,lenType:"FIXED",description:"Message authentication code"}
    ]