let v={
    "fields":{
        "0":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"MTI"},
        "1":{"contentType":"b","maxLen":8,"lenType":"FIXED","description":"Bitmap"},
        "2":{"contentType":"n","maxLen":19,"lenType":"LLVAR","description":"Primary account number (PAN)"},
        "3":{"contentType":"n","maxLen":6,"lenType":"FIXED","description":"Processing code"},
        "4":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Amount, transaction"},
        "5":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Amount, settlement"},
        "6":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Amount, cardholder billing"},
        "7":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Transmission date & time (MMDDhhmmss)"},
        "8":{"contentType":"n","maxLen":8,"lenType":"FIXED","description":"Amount, cardholder billing fee"},
        "9":{"contentType":"n","maxLen":8,"lenType":"FIXED","description":"Conversion rate, settlement"},
        "10":{"contentType":"n","maxLen":8,"lenType":"FIXED","description":"Conversion rate, cardholder billing"},
        "11":{"contentType":"n","maxLen":6,"lenType":"FIXED","description":"System trace audit number"},
        "12":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Time, local transaction (YYMMDDhhmmss)"},
        "13":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Date, local transaction (MMDD)"},
        "14":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Date, expiration"},
        "15":{"contentType":"n","maxLen":6,"lenType":"FIXED","description":"Date, settlement"},
        "16":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Date, conversion"},
        "17":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Date, capture"},
        "18":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Merchant type"},
        "19":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Acquiring institution country code"},
        "20":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"PAN extended, country code"},
        "21":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Forwarding institution. country code"},
        "22":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Point of service entry mode"},
        "23":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Application PAN sequence number"},
        "24":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Network International identifier (NII)"},
        "25":{"contentType":"n","maxLen":2,"lenType":"FIXED","description":"Point of service condition code"},
        "26":{"contentType":"n","maxLen":2,"lenType":"FIXED","description":"Point of service capture code"},
        "27":{"contentType":"n","maxLen":1,"lenType":"FIXED","description":"Authorizing identification response length"},
        "28":{"contentType":"an","maxLen":9,"lenType":"FIXED","description":"Amount, transaction fee"},
        "29":{"contentType":"an","maxLen":9,"lenType":"FIXED","description":"Amount, settlement fee"},
        "30":{"contentType":"an","maxLen":9,"lenType":"FIXED","description":"Amount, transaction processing fee"},
        "31":{"contentType":"an","maxLen":9,"lenType":"FIXED","description":"Amount, settlement processing fee"},
        "32":{"contentType":"n","maxLen":11,"lenType":"LLVAR","description":"Acquiring institution identification code"},
        "33":{"contentType":"n","maxLen":11,"lenType":"LLVAR","description":"Forwarding institution identification code"},
        "34":{"contentType":"ns","maxLen":28,"lenType":"LLVAR","description":"Primary account number, extended"},
        "35":{"contentType":"z","maxLen":37,"lenType":"LLVAR","description":"Track 2 data"},
        "36":{"contentType":"n","maxLen":104,"lenType":"LLLVAR","description":"Track 3 data"},
        "37":{"contentType":"an","maxLen":12,"lenType":"FIXED","description":"Retrieval reference number"},
        "38":{"contentType":"an","maxLen":6,"lenType":"FIXED","description":"Authorization identification response"},
        "39":{"contentType":"an","maxLen":3,"lenType":"FIXED","description":"Response code"},
        "40":{"contentType":"an","maxLen":3,"lenType":"FIXED","description":"Service restriction code"},
        "41":{"contentType":"ans","maxLen":8,"lenType":"FIXED","description":"Terminal ID"},
        "42":{"contentType":"ans","maxLen":15,"lenType":"FIXED","description":"Merchant number"},
        "43":{"contentType":"ans","maxLen":40,"lenType":"FIXED","description":"Card acceptor name/location"},
        "44":{"contentType":"an","maxLen":25,"lenType":"LLVAR","description":"Additional response data"},
        "45":{"contentType":"an","maxLen":76,"lenType":"LLVAR","description":"Track 1 data"},
        "46":{"contentType":"an","maxLen":999,"lenType":"LLLVAR","description":"Amount, fees"},
        "47":{"contentType":"an","maxLen":999,"lenType":"LLLVAR","description":"Additional data"},
        "48":{"contentType":"an","maxLen":999,"lenType":"LLLVAR","description":"Additional data - private"},
        "49":{"contentType":"an","maxLen":3,"lenType":"FIXED","description":"Currency code, transaction"},
        "50":{"contentType":"an","maxLen":3,"lenType":"FIXED","description":"Currency code, settlement"},
        "51":{"contentType":"an","maxLen":3,"lenType":"FIXED","description":"Currency code, cardholder billing"},
        "52":{"contentType":"b","maxLen":16,"lenType":"FIXED","description":"PIN data"},
        "53":{"contentType":"an","maxLen":99,"lenType":"LLVAR","description":"Security related control information"},
        "54":{"contentType":"an","maxLen":120,"lenType":"LLLVAR","description":"Additional amounts"},
        "55":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"ICC Sys Related Data"},
        "56":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved ISO"},
        "57":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved national"},
        "58":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved national"},
        "59":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved national"},
        "60":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved national"},
        "61":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved private"},
        "62":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved private"},
        "63":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved private"},
        "64":{"contentType":"b","maxLen":8,"lenType":"FIXED","description":"Message authentication code (MAC)"},
        "65":{"contentType":"b","maxLen":1,"lenType":"FIXED","description":"Bitmap, extended"},
        "66":{"contentType":"n","maxLen":1,"lenType":"FIXED","description":"Settlement code"},
        "67":{"contentType":"n","maxLen":2,"lenType":"FIXED","description":"Extended payment code"},
        "68":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Receiving institution country code"},
        "69":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Settlement institution country code"},
        "70":{"contentType":"n","maxLen":3,"lenType":"FIXED","description":"Network management information code"},
        "71":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Message number"},
        "72":{"contentType":"n","maxLen":4,"lenType":"FIXED","description":"Message number, last"},
        "73":{"contentType":"n","maxLen":6,"lenType":"FIXED","description":"Date, action (YYMMDD)"},
        "74":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Credits, number"},
        "75":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Credits, reversal number"},
        "76":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Debits, number"},
        "77":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Debits, reversal number"},
        "78":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Transfer number"},
        "79":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Transfer, reversal number"},
        "80":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Inquiries number"},
        "81":{"contentType":"n","maxLen":10,"lenType":"FIXED","description":"Authorizations, number"},
        "82":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Credits, processing fee amount"},
        "83":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Credits, transaction fee amount"},
        "84":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Debits, processing fee amount"},
        "85":{"contentType":"n","maxLen":12,"lenType":"FIXED","description":"Debits, transaction fee amount"},
        "86":{"contentType":"n","maxLen":16,"lenType":"FIXED","description":"Credits, amount"},
        "87":{"contentType":"n","maxLen":16,"lenType":"FIXED","description":"Credits, reversal amount"},
        "88":{"contentType":"n","maxLen":16,"lenType":"FIXED","description":"Debits, amount"},
        "89":{"contentType":"n","maxLen":16,"lenType":"FIXED","description":"Debits, reversal amount"},
        "90":{"contentType":"n","maxLen":42,"lenType":"FIXED","description":"Original data elements"},
        "91":{"contentType":"an","maxLen":1,"lenType":"FIXED","description":"File update code"},
        "92":{"contentType":"an","maxLen":2,"lenType":"FIXED","description":"File security code"},
        "93":{"contentType":"an","maxLen":5,"lenType":"FIXED","description":"Response indicator"},
        "94":{"contentType":"an","maxLen":7,"lenType":"FIXED","description":"Service indicator"},
        "95":{"contentType":"an","maxLen":42,"lenType":"FIXED","description":"Replacement amounts"},
        "96":{"contentType":"b","maxLen":8,"lenType":"FIXED","description":"Message security code"},
        "97":{"contentType":"an","maxLen":17,"lenType":"FIXED","description":"Amount, net settlement"},
        "98":{"contentType":"ans","maxLen":25,"lenType":"FIXED","description":"Payee"},
        "99":{"contentType":"n","maxLen":11,"lenType":"LLVAR","description":"Settlement institution identification code"},
        "100":{"contentType":"n","maxLen":11,"lenType":"LLVAR","description":"Receiving institution identification code"},
        "101":{"contentType":"ans","maxLen":17,"lenType":"LLVAR","description":"File name"},
        "102":{"contentType":"ans","maxLen":28,"lenType":"LLVAR","description":"Account identification 1"},
        "103":{"contentType":"ans","maxLen":28,"lenType":"LLVAR","description":"Account identification 2"},
        "104":{"contentType":"ans","maxLen":100,"lenType":"LLLVAR","description":"Transaction description"},
        "105":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "106":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "107":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "108":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "109":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "110":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "111":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for ISO use"},
        "112":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "113":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "114":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "115":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "116":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "117":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "118":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "119":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for national use"},
        "120":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "121":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "122":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "123":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "124":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "125":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "126":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "127":{"contentType":"ans","maxLen":999,"lenType":"LLLVAR","description":"Reserved for private use"},
        "128":{"contentType":"b","maxLen":8,"lenType":"FIXED","description":"Message authentication code"}
    },
    "code_response":{
        "100":"CARD DECLINED",
        "101":"EXPIRED CARD",
        "103":"CALL ISSUER",
        "104":"CAPTURE CARD SPEC",
        "106":"PIN-TRIES EXCEED",
        "107":"CALL ISSUER",
        "109":"INVALID TERMINAL OR MERCHANT",
        "110":"INVALID AMOUNT",
        "111":"INVALID CARD",
        "116":"INSUFFICIENT FUNDS",
        "117":"INCORRECT PIN",
        "119":"SECURITY VIOLATION",
        "120":"SECURITY VIOLATION",
        "121":"EXCDS WDRWL LIMT",
        "123":"EXCDS WDRWL LIMT",
        "125":"INVALID CARD",
        "202":"INVALID CARD",
        "203":"PICK-UP CARD",
        "204":"PICK-UP CARD",
        "208":"PICK-UP CARD",
        "209":"PICK-UP CARD",
        "802":"NOT HONOR",
        "902":"INVALID TRANS",
        "903":"RE-ENTER TRANS",
        "904":"FORMAT ERROR",
        "907":"HOST NOT AVAIL.",
        "909":"INVALID TRANS",
        "910":"HOST NOT AVAIL.",
        "913":"INVALID TRANS",
        "914":"ORIG TRANS NOT FOUND",
        "920":"PIN ERROR","940":"CAPTURE CARD SPEC",
        "00":"APPROVED","000":"APPROVED","001":"HONR W/ID:",
        "005":"UNABLE TO PROCESS","020":"BALANCE IS NEGATIVE"
    },
    "data_type":{"BIN":[1,52,53,55]},
    "rules":{"restrinct":{"message_type":["0500","1200"],"processing_code":["02"],"BIN":["60128981"],"PAN":["4221300000000282"]},"required":{"message_type":{"0801":["24","25"],"0100":["24"],"0200":["24"],"0400":["24"]},"processing_code":{"00":["3","4"],"03":["3"]}},"response":{"Fonction_code":{}}},"messageType":{"1100":"Authorization request","1101":"Authorization request repeat","1110":"Authorization request response","1120":"Authorization advice","1121":"Authorization advice repeat","1130":"Authorization advice response","1200":"Financial request","1201":"Financial request repeat","1202":"Financial completion request","1203":"Financial completion request Repeat","1210":"Financial request response","1212":"Financial completion response","1220":"Financial Transaction Advice","1221":"Financial Transaction Advice Repeat","1230":"Financial Transaction advice response","1320":"Acquirer File Update Advice","1321":"Acquirer File Update Advice Repeat","1322":"Issuer file update advice","1323":"Issuer file update advice repeat","1330":"Acquirer File Update Advice Response","1332":"Issuer File Update Advice Response","1400":"Reversal request","1401":"Reversal request Repeat","1410":"Reversal request response","1420":"Reversal advice","1421":"Reversal advice Repeat","1430":"Reversal advice response","1500":"Acquirer reconciliation request","1501":"Acquirer reconciliation request Repeat","1510":"Acquirer reconciliation request response","1520":"Acquirer reconciliation advice","1521":"Acquirer reconciliation advice repeat","1522":"Card issuer reconciliation advice","1523":"Card issuer reconciliation advice repeat","1530":"Acquirer reconciliation advice response","1532":"Card issuer reconciliation advice response","1600":"Administration request","1601":"Administration request repeat","1610":"Administration response","1620":"Administration advice","1621":"Administration advice repeat","1630":"Administration advice response","1800":"Network Management request","1801":"Network Management request repeat","1810":"Network Management request response","1820":"Network Management advice"}}